contact_links:
- name: Visit the Serilog Repository
  url: https://github.com/serilog/serilog
  about: Official Serilog repository for Serilog-specific help & assistance
- name: Visit the Serilog Wiki
  url: https://github.com/serilog/serilog/wiki
  about: Official wiki page for Serilog, provides you with more complex examples, though there's no guarentee they work wit v2.12.0
