contact_links:
- name: Serilog Repository
  url: https://github.com/serilog/serilog
  about: Visit the official Serilog repository for help & assitance
- name: Serilog Wiki
  url: https://github.com/serilog/serilog/wiki
  about: Visit the official wiki page for Serilog, provides you with more complex examples, though there's no guarentee they work wit v2.12.0
